#!/usr/bin/env bash

TEMP_EXT=(aux bbl blg glg glo gls glsdefs ist lal lol loc loi lod loq out toc log synctex.gz dvi brf lon bit lof lot glx gxg gxs idx ilg ind url svn)

for ext in ${TEMP_EXT[@]}
do
  find . -type f -name "*.$ext" -delete
done
